name: shadermorph_flutter
description: "GPU-powered morph transitions for Flutter single-page and cross-route flows."
version: 0.0.1
homepage: https://github.com/Rimotli-tech/shadermorph
repository: https://github.com/Rimotli-tech/shadermorph
issue_tracker: https://github.com/Rimotli-tech/shadermorph/issues
topics:
  - flutter
  - animation
  - shader
  - transition
  - navigation

environment:
  sdk: ^3.10.7
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  shaders:
    - shaders/shader_engine.frag
    - shaders/shader_engine_v2.frag
    - shaders/shader_engine_shape_aware.frag
