name: shadermorph_flutter
description: "ShaderMorph is a cross-platform GPU transition engine."
version: 0.0.1
homepage:

environment:
  sdk: ^3.10.7
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  shaders:
    - core_shaders/engine/shader_engine.frag
